/*

 Includes:

 Sizzle CSS Selector Engine
 Copyright 2011, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.
 More information: http://sizzlejs.com/
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2012 VigLink. Rights reserved and patent(s) pending.
*/
(function(g){var d,c;c={each:function(a,b){var c,h;for(c=0,h=a.length;c<h;c++)b(a[c],c)},extend:function(a){var b,c,h,l,k=arguments.length,a=a||{};for(c=1;c<k;c++)if(l=arguments[c],void 0!==l&&null!==l)for(h in l)b=l[h],a!==b&&void 0!==b&&(a[h]=b);return a},noop:function(){}};c.extend(c,{addClass:function(a,b){c.hasClass(a,b)||(a.className=(a.className?a.className+" ":"")+b)},attrValues:function(a,b,c){return(b=a[b])?b.split(c||" "):[]},bind:function(a,b){return function(){return a.apply(b,arguments)}},
browser:function(){var a={},b,e=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);c.each(e,function(c){b=(/[\/ :]([^\/ :]+)$/.exec(c)||[])[1];a[b?c.substr(0,c.length-b.length-1).replace(/\d*$/,""):c]=b||!0});return{aol:a.aol,blackberry:a.blackberry,ie:a.msie,ios:a.mobile&&a.safari,opera:a.opera,playstation:a.playstation,version:parseFloat(a.version||a.crios)||!1}}(),cache:function(){var a={},b="vglnk_"+(new Date).getTime(),
c=0;return function(h,l,k){if(h){var d=h[b];if(d||void 0!==k)return d||(d=++c),a[d]||(h[b]=d,a[d]={}),void 0!==k&&(a[d][l]=k),"string"===typeof l?a[d][l]:a[d]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=c.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return c.extend({},a)},contains:function(a,b){return-1!==c.indexOf(a,b)},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},
contextIsAncestor:function(a){for(var b=window.self;b.parent&&b.parent!==b;)if(b=b.parent,b===a)return!0;return!1},cors:function(a){var b,c=function(){eval(b.responseText)};b=new window.XMLHttpRequest;b.onreadystatechange=function(){4===b.readyState&&200===b.status&&c()};b.open("GET",a);b.withCredentials=!0;b.send()},createA:function(a,b){return c.createEl("a",{href:a,target:b})},createEl:function(a,b,e,h){var l,a=(h||document).createElement(a),b=b||{},e=e||{};for(l in b)void 0!==b[l]&&(a[l]=b[l]);
c.css(a,e);return a},css:function(a,b){for(var c in b)try{a.style[c]=b[c]}catch(h){}return a},destructing:function(a){return function(a){var c=!1,h;return function(){c||(h=a.apply(null,arguments),c=!0);return h}}(a)},escapeRegExp:function(){var a;return function(b){a=a||RegExp("([.*+?^${}()|[\\]\\\\])","g");return b.replace(a,"\\$1")}}(),eventLink:function(a){var b,c=a.target||a.srcElement;do{try{b=c.nodeType}catch(h){break}if(1===b&&(a=c.tagName.toUpperCase(),"A"===a||"AREA"===a))return c;c=c.parentNode}while(c)},
exceptionLogger:function(){var a=!1,b=c.noop;return function(c,h){if(void 0!==h)a=h,b=c;else return function(){if(a)try{return c.apply(this,arguments)}catch(h){b(h)}else return c.apply(this,arguments)}}}(),fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));var a=a.split("&"),b={};c.each(a,function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return b},geometry:function(){var a,b=arguments.length,e=Infinity,h=Infinity,l=-Infinity,k=-Infinity,d;for(a=0;a<b;a++)d=
c.position(arguments[a]),e=Math.min(e,d.x),h=Math.min(h,d.y),l=Math.max(l,d.x+arguments[a].offsetWidth),k=Math.max(k,d.y+arguments[a].offsetHeight);return{x:e,y:h,w:l-e,h:k-h,x1:e,y1:h,x2:l,y2:k}},hasAttrValue:function(a,b,e,h){return b?c.contains(c.attrValues(a,b,h),e):!1},hasClass:function(a,b){return c.hasAttrValue(a,"className",b)},hasRel:function(a,b){return c.hasAttrValue(a,"rel",b)},indexOf:function(){return Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b)}:function(a,
b){var c,h;for(c=0,h=a.length;c<h;c++)if(a[c]===b)return c;return-1}}(),isArray:function(a){return"array"===c.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var b=document.getElementsByTagName("script")[0],a=c.createEl("script",{type:"text/javascript",src:a});b.parentNode.insertBefore(a,b)},map:function(a,b){var e=[];c.each(a,function(a,c){void 0!==a&&(e[c]=b(a))});return e},on:function(){var a;
return function(b,e,h){var l,k;if(1===arguments.length)a=b;else{if(2===arguments.length){if(!a)return;h=e;e=b;b=a}try{l=b["on"+e]}catch(d){}"function"===typeof l&&(b["on"+e]=c.bind(function(a){var a=a||window.event,e=l.apply(b,arguments);this.exceptionLogger(function(){return a?(void 0!==e&&!1!==a.returnValue&&(a.returnValue=e),c.isDefaultPrevented(a)&&"function"===c.type(a.preventDefault)&&a.preventDefault(),a.returnValue):e})()},this));k=c.exceptionLogger(function(){if(a.enabled())return h.apply(null,
arguments)});b.addEventListener?b.addEventListener(e,k,!1):b.attachEvent&&b.attachEvent("on"+e,k)}}}(),position:function(a){var b,c=0,h=0,l=0,k=0;if(!a.offsetParent)return!1;b=a;do c+=b.offsetLeft,h+=b.offsetTop,b=b.offsetParent;while(b);b=a;do l+=b.scrollLeft,k+=b.scrollTop,b=b.parentNode;while(b&&b!==document.body);return{x:c-l,y:h-k}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},ready:function(){var a=!1,b=[],e=!1,h,l,k,d,f;document.addEventListener?
k=function(){document.removeEventListener("DOMContentLoaded",k,!1);f()}:document.attachEvent&&(d=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",d),f())});h=function(){if(!a){a=!0;if("complete"===document.readyState)return f();if(document.addEventListener)document.addEventListener("DOMContentLoaded",k,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",d);var b=!1;try{b=null===window.frameElement}catch(e){}document.documentElement.doScroll&&
b&&l()}c.on(window,"load",f)}};l=function(){if(!e){try{document.documentElement.doScroll("left")}catch(a){setTimeout(c.exceptionLogger(l),1);return}f()}};f=function(){if(!e){if(!document.body)return setTimeout(c.exceptionLogger(f),13);e=!0;b&&(c.each(b,function(a){a()}),b=null)}};return function(a){h();e?a():b.push(a)}}(),reformatKeys:function(a){var b,e,h=function(a){return"_"+a.toLowerCase()};for(b in a)e=b.replace(/([A-Z])/g,h),"object"===c.type(a[b])&&(a[b]=c.reformatKeys(a[b])),e!==b&&(a[e]=
a[b],delete a[b]);return a},removeClass:function(a,b){if(c.hasClass(a,b)){var e,h,d=c.attrValues(a,"className");for(e=0,h=d.length;e<h;e++)d[e]===b&&delete d[e];a.className=d.join(" ")}},request:function(a,b,e){var h,d,e=c.extend({fn:c.noop,"return":!1,timeout:null},e);"string"===typeof e.fn?b=c.extend(b,{jsonp:e.fn}):"function"===typeof e.fn&&(h=c.destructing(e.fn),d=c.uniqid("vglnk_jsonp_"),b=c.extend(b,{jsonp:d}),window[d]=c.exceptionLogger(function(){h.apply(this,arguments);window[d]=void 0}),
null!==e.timeout&&setTimeout(c.exceptionLogger(h),e.timeout));b=c.extend({format:"jsonp"},b);b=c.toQuery(b);a=a+(b.length?"?":"")+b;return e["return"]?a:c.traits.cors?c.cors(a):c.jsonp(a)},toQuery:function(a){var b,c="";for(b in a)null!==a[b]&&void 0!==a[b]&&(c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a[b]));return c.substr(1)},transmitsPII:function(a){return c.containsPII(a+" "+document.referrer)},type:function(a){return null===a?"null":void 0===a?"undefined":Object.prototype.toString.call(a).slice(8,
-1).toLowerCase()},updateUrl:function(a,b){return c.extend(c.createA(a),b).href},uniqid:function(){var a=0;return function(b){return(b||"")+(new Date).getTime()+a++}}()});c.traits={basicCompatibility:!(c.browser.blackberry||c.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!(c.browser.ios&&c.browser.version&&(5>c.browser.version||5<c.browser.version)),jsRedirectSetsReferrer:c.browser.aol||!(c.browser.ie||c.browser.opera),
quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var f,o,m;d={api:function(a,b,e){a=f.api_url+"/"+a;b=c.extend({cuid:f.cuid,key:f.key,drKey:f.key?null:f.dr_key,loc:location.href,subId:f.sub_id,v:1},b);b.subId&&b.key!==f.key&&(b.subId=null);return c.request(a,b,e)},addEventListener:function(a,b){this.fire(a,b)},click:function(){var a=function(a){if("_self"===a)return window.self;if(c.traits.crossWindowCommunication&&c.traits.jsRedirectSetsReferrer)return a=
window.open("",a),a.focus(),a},b=function(a){var b=a.previousSibling,l=a.nextSibling,k=["",a.textContent,""];void 0!==k[1]&&(k[0]=b&&3===b.nodeType?b.data:"",k[2]=l&&3===l.nodeType?l.data:"",k=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,
b,c]}.apply(this,k),""!==k[0]&&""!==k[2]&&(k[0]=k[0].split(" ").reverse().slice(0,10+(" "===k[0].substr(k[0].length-1,1)?1:0)).reverse().join(" "),k[2]=k[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(c.cache(a,"params")||{}).type,before:k[0],after:k[2],txt:k[1],loc:location.href,out:a.href,v:2},d.log("info",c.toQuery(a))))};return function(e,h){var h=e.target||h,h=!h||h===window.name||"_top"===h&&window.top===window.self||"_parent"===h&&window.parent===window.self?"_self":h,d,k,g=a(h),
m;if("_self"!==h&&(!c.traits.crossWindowCommunication||!c.traits.jsRedirectSetsReferrer))m="go";else try{if(void 0===g.document)throw!0;m="jsonp"}catch(o){m="go"}d=c.destructing(c.bind(function(){f.time_click&&arguments.length&&this.logTime("clk");var a=Array.prototype.slice.call(arguments);a.unshift(e,g,h);this.onApiClick.apply(this,a)},this));c.cache(this,"link","string"===typeof e?e:e.href);if("string"===typeof e&&(e=c.createA(e,h),!this.preprocessLink(e))||!f.enabled)return d();k=this.clickParams(e,
m);this.logTime();f.log_context&&b(e);if("go"===m)this.redirect(this.api("click",k,{"return":!0}),g,h);else if(g===window.self)this.api("click",k,{fn:d,timeout:f.click_timeout});else{if(c.contextIsAncestor(g))return this.redirect(e.href,g,h);d=c.exceptionLogger(d);setTimeout(function(){d()},f.click_timeout);g.document.open();g.callback=d;g.document.write("<html><head><title>"+e.href+'</title><script type="text/javascript" src="'+this.api("click",k,{fn:"callback","return":!0})+'"><\/script></head></html>');
g.document.close()}}}(),clickParams:function(a,b){var e=c.extend(c.cache(a,"params"),{format:b,libid:f.library_id,out:a.href,ref:document.referrer||null,reaf:f.reaffiliate||null,title:document.title,txt:a.innerHTML});128<e.txt.length&&(e.txt=e.txt.replace(/<[^>]+>/g,""),e.txt=128<e.txt.length?e.txt.substr(0,125)+"...":e.txt);return e},enabled:function(){if(f.enabled&&o!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))f.enabled=!1;return f.enabled},expose:function(a,b){if(b=
b||this[a])"function"===typeof b?b=c.exceptionLogger(c.bind(b,this)):"object"===typeof b&&(b=c.clone(b)),m[a]||(m[a]=b)},fire:function(){var a={};return function(b,e){var b=b.toLowerCase(),d=a[b]||{fired:!1,listeners:[]};"function"===typeof e?d.fired?e({type:b}):d.listeners.push(e):(d.fired=!0,c.each(d.listeners,function(a){"function"===typeof a&&a({type:b})}),d.listeners=[]);a[b]=d}}(),handleRightClick:function(a,b){if(f.rewrite_modified&&a&&b)switch(b){case "setup":c.cache(a,"href")||c.cache(a,
"href",a.href);a.href=this.api("click",this.clickParams(a,"go"),{"return":!0});setTimeout(c.exceptionLogger(c.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=c.cache(a,"href"),c.cache(a,"href",null)}},harmony:function(){c.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};return function(a){return f.harmony_level<=a}}(),init:c.exceptionLogger(function(){return function(){var a=!0===document.__v5k;document.__v5k=!0;a||(this.initLibEvents(),this.initNamespace(),
this.initOptions(),c.exceptionLogger(c.bind(this.logException,this),!f.dev),this.initDRApi(),this.initApi(),this.enabled()&&(this.initLegacyCallbacks(),this.ping()))}}()),initApi:function(){var a,b={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(b[a]=window.vglnk[a]);m=o[g]=c.noop;this.expose("click");this.expose("link",d.preprocessLink);this.expose("opt");this.expose("$",c.clone(c));c.extend(m,m===window.vglnk?b:{})},initDRApi:function(){var a=!1;window.DrivingRevenue=c.exceptionLogger(c.destructing(c.bind(function(){a=
!0;f.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));c.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initLibEvents:function(){c.on(d);c.ready(c.bind(function(){this.fire("DOMReady")},this))},initNamespace:function(){window.vglnk&&window.vglnk.key&&(g="vglnk");var a=window,b=g.split("."),c;for(g=b.pop();0<b.length;)c=b.shift(),a[c]=a[c]||{},a=a[c];o=a;m=o[g]=o[g]||{}},initOptions:function(){var a;this.initLegacyOptions();f=c.extend(this.publicOptions({api_url:"//api.viglink.com/api",
cuid:null,dev:!1,dr_key:null,enabled:c.traits.basicCompatibility,key:null,partner:null,sub_id:null,reaffiliate:!1,harmony_level:0,rewrite_original:!0,rewrite_modified:!1}),f,m,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{}},swap:{},time_click:!1,time_ping:!1});for(a in f)"_plugin"===a.substr(-7)&&delete f[a]},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",
vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(m[b[a]]=window[a],"vglnk_domain"===a&&(m[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,b={vl_cB:c.bind(this.onApiClick,this),vl_disable:function(){f.enabled=!1}};for(a in b)window[a]=b[a]},initLinks:function(){c.each(document.links,c.bind(this.preprocessLink,this))},initPlugins:function(){var a,b=1,e=[],h=function(){var k=[],f=function(a){return function(){if(a){var b=Array.prototype.slice.call(arguments);
b.unshift("custom",a);d.log.apply(this,b)}}};a=null;c.each(e,function(a){var b;b=a[0];var e=a[1],i=a[2];(b=window.vglnk&&window.vglnk[b+"_plugin"])?(a="function"===c.type(b.run)?b.run:b,b="function"===c.type(b.setup)?b.setup:null,e&&1===e.mode?(b&&b(e,c.clone(c),m,f(e.key)),delete e.mode):a&&(b&&!i&&b(e,c.clone(c),m,f(e.key)),a(e,c.clone(c),m,f(e.key)))):k.push(a)});e=k;0<e.length&&(a=setTimeout(c.exceptionLogger(h),Math.min(Math.max(Math.pow(2,++b),100),5E3)))},f=function(c,d){return function(c,
d){return function(){e.push([c,d,!0]);b=1;clearTimeout(a);h()}}(c,d)};return function(a){for(var b in a)"object"===typeof a[b]&&!1!==a[b].enabled&&(e.push([b,a[b]]),1===a[b].mode&&this.expose("init_"+b,f(b,a[b])));h()}}(),isRewritable:function(){var a=c.canonicalizeHostname(document.location);return function(b){var e,d="";try{e=b.hostname,d=b.protocol,e.charAt(0)}catch(l){return!1}""!==e&&(e=c.canonicalizeHostname(b));return!(""===e||a===e||!d.match(/^https?:$/i)||f.norewrite[e]||!f.rewrite_original&&
!c.cache(b,"type")||c.hasRel(b,"norewrite")||c.hasRel(b,"noskim"))}}(),initEvents:c.destructing(function(){var a={left:d.onClick,right:d.onContextmenu},b={left:c.noop,right:c.noop},e=c.traits.windowLevelHandlers?window:document,h=function(e){e=e||window.event;if((e=c.eventLink(e))&&!c.cache(e,"evented"))f(e,d.harmony(c.harmony.LINK_LEVEL_EVENTS)?a:b),c.cache(e,"evented",!0)},f=function(a,b){c.on(a,"click",c.bind(b.left,d));c.on(a,"contextmenu",c.bind(b.right,d))};c.on(e,"copy",c.bind(d.onCopy,d));
c.on(e,"mousedown",h);if(d.harmony(c.harmony.LINK_LEVEL_EVENTS))c.on("DOMReady",function(){c.each(document.links,function(a){c.on(a,"mousedown",h)})});(!c.traits.quirksMode||d.harmony(c.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&f(e,a)}),log:function(a,b,e,d){var g,k=c.toQuery({nocache:c.uniqid()});g="pixel.gif";if("custom"===a)k+="&"+c.toQuery({key:b,type:e}),c.each("array"===c.type(d)?d:[d],function(a){c.each(["e","i","o"],function(b){delete a[b]});k+="&"+c.toQuery(a)});else{k+="&"+c.toQuery({key:f.key,
drKey:f.key?null:f.dr_key});if("time"===a)g="time.gif",a={libId:f.library_id,time:e,type:b};else if("exception"===a)a={e:b,o:e};else if("info"===a)a={i:b};else return;k+="&"+c.toQuery(a)}g=f.api_url+"/"+g+"?"+k;c.transmitsPII(g)||(c.createEl("img").src=g)},logException:function(a){if(f.debug){var b={link:c.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?b.message=a:b=c.extend(b,a);this.log("exception",a,c.toQuery(b))}},logTime:function(){var a;return function(b){0===
arguments.length?a=(new Date).getTime():this.log("time",b,(new Date).getTime()-a)}}(),onApiClick:function(a,b,e,d,g){var k=d||a.href,d=c.bind(function(){this.redirect(k,b,e)},this);"object"===typeof g&&(g.tracking||g.image)?(a=c.createEl(g.tracking?"iframe":"img",{src:g.tracking||g.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(a),setTimeout(c.exceptionLogger(d),g.timeout||f.hop_timeout)):d()},onApiPing:function(a,b,e,h,g,k){f.rewrite_original=!1;var g=c.reformatKeys(g||
{}),m,o,q;o=function(a){var b={},n=function(a){c.isArray(a)?b[a[0]]=a[1]:b[a]=1};c.isArray(a)&&c.each(a,n);return b};q=c.extend(f.plugins,g.plugins);f=c.extend(f,g);delete f.plugins;f.library_id=a;f.click_timeout=b;f.time_ping&&this.logTime("png");c.extend(f.norewrite,o(e));c.extend(f.swap,o(h));c.extend(f.nofollow,o(k));for(m in f)"on"===m.toLowerCase().substr(0,2)&&2<m.length&&"function"===c.type(f[m])&&(c.on(d,m.toLowerCase().substr(2),c.bind(f[m],window)),delete f[m]);this.initPlugins(q);this.initLinks();
this.initEvents();this.fire("libready")},onClick:function(a){var a=a||window.event,b=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,e=a.which&&1===a.which||0===a.button,d=c.eventLink(a);if(d&&this.isRewritable(d)&&!b&&e&&!c.isDefaultPrevented(a))return this.click(d),c.preventDefault(a)},onContextmenu:function(a){(a=c.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(){var a,b,e,f,g=[];if(window.getSelection){e=window.getSelection();for(a=0,b=e.rangeCount;a<
b;a++){try{f=e.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(k){}0<f.length&&128>=f.length&&g.push(f)}}c.each(g,function(a){d.log("info",c.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(f[a]=b);return f[a]},ping:function(){var a=!1;return function(){if(!a&&(f.key||f.dr_key))a=!0,c.transmitsPII(this.api("ping",null,{"return":!0}))||(this.logTime(),this.api("ping",null,{fn:c.bind(this.onApiPing,
this)}))}}(),preprocessLink:function(a){if(this.isRewritable(a)){var b;b=c.createA(f.api_url);if("/api/click"===a.pathname&&(a.hostname===b.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))b=c.fromQuery(a.search),void 0!==b.out&&(a.href=b.out,delete b.out,c.cache(a,"params",b));f.swap[a.href]&&(a.href=f.swap[a.href]);f.nofollow[a.href]&&!c.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow");window.IPBoard&&window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&
c.hasRel(a,"external")&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank");return a}},publicOptions:function(){var a={};return function(b){"object"===c.type(b)&&(a=b);return c.extend({},a)}}(),redirect:function(a,b,e){!c.traits.crossWindowCommunication&&!b?(e=window.open(a,e),e.focus()):c.traits.jsRedirectSetsReferrer?setTimeout(c.exceptionLogger(function(){!b||b===window.self?window.location=a:c.contextIsAncestor(b)?b.location=a:b.location.replace(a)}),0):("_blank"===e&&(e=c.uniqid("win_")),
e=c.createA(a,e),e.rel="norewrite",document.body.appendChild(e),e.click(),e.parentNode.removeChild(e))}};d.init();try{delete window.vglnk_self}catch(q){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};window.vglnk.link_affiliation_plugin={run:function(g,d,c){c.opt("rewrite_original",!0)}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin={run:function(g,d,c){c.opt("rewrite_modified",!0)}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin={run:function(g,d,c){if(g.key){var f={init:function(){d.each(this.getDRSearchForms(),function(c){if(!d.cache(c,"evented")){var g=f.getInput(c),q=function(){g.value||d.css(g,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};d.cache(c,"evented",!0);c.onsubmit=null;g.onfocus=null;g.onblur=null;d.on(g,"focus",function(){d.css(g,{"background-image":"none"})});d.on(g,"blur",q);q();d.on(c,"submit",function(a){f.onSubmit(a,c)})}})},getDRSearchForms:function(){var c=
[];d.each(document.getElementsByTagName("form"),function(d){f.getInput(d)&&d.id.match(/^DR-ebay-search(CSS|2)?$/i)&&c.push(d)});return c},getInput:function(c){return c.p||c.q2},onSubmit:function(o,m){var o=o||window.event,q="http://shop.ebay.com/i.html?"+d.toQuery({_nkw:f.getInput(m).value}),q=d.createA(q,"_blank");d.cache(q,"params",{key:g.key});c.click(q);return d.preventDefault(o)}};f.init();d.on("DOMReady",d.bind(f.init,f))}}};window.vglnk=window.vglnk||{};
window.vglnk.page_harmony_plugin={run:function(g,d,c){g=parseInt(g.level,10);isFinite(g)&&c.opt("harmony_level",g)}};window.vglnk=window.vglnk||{};
window.vglnk.product_linker_plugin=function(){var g,d,c,f,o,m,q=null,a={},b,e=0,h=0,l=0,k=0,y={setup:function(u,s,w,i){d=s;c=w;f=i;g=d.extend({cat:null,platform:null,api_url:d.updateUrl(c.opt("api_url"),{pathname:"/api/insert"}),key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:1,ui:!0},u);!g.api_url||!g.key||!(g.platform&&2===g.type||1===g.type||3===g.type)?y.run=d.noop:(d=d.extend(d,{createWrapper:function(a){var b,
i=d.createEl("div");if(i.outerHTML)return b=d.createEl("div"),i.appendChild(b),b.outerHTML="<pre>"+a+"</pre>",i.childNodes[0];i.innerHTML=a;return i},select:window.vglnk.Sizzle||function(){return[]}}),o={bbp:{id_finder:["li",/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content, .postbody .signature"},ubb:{id_finder:["a",
/^Post(\d+)$/,"name"],scope:".post_inner *[id^='body'], .post_inner .signature"},vb3:{id_finder:["td",/^td_post_(\d+)$/],scope:"td[id^='td_post_'] div[id^='post_message_'],td[id^='td_post_'] div[id^='post_message_'] ~ div:not([class])"},vb4:{id_finder:["li",/^post_(\d+)$/],scope:".postbody .content, .postbody .signature, .post-content, ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],scope:null}}[g.platform]||{},m={addPhrasesToMatcher:function(a){var i="";"regexp"===d.type(a)?
i=a.source:"array"===d.type(a)&&(i="(?:^|[\\s\"'\\(])("+d.map(a,d.escapeRegExp).join("|")+")(?=\\s|\\W*$|\\W{2})");""!==i&&(b=RegExp(b?"(?:"+i+"|"+b.source+")":i,"i"))},focusLink:function(a){a.id||(a.id=d.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPhrases:function(a){d.request(g.api_url,d.extend(m.getPartnerParams(),{cat:g.cat,key:g.key,mode:g.mode,pt:g.platform,ps:g.product_source,i:a?a.join("|"):null,u:location.href,type:g.type}),{fn:d.bind(m.onInsertApi,m)})},getPartnerParams:function(){var a,
b,i=c.opt("partner"),j={};for(a in i)break;if(a)for(b in i[a])j[a+"_"+b]=i[a][b];return j},getPostIDs:function(){var a=[],b=o?o.id_finder:null;b&&d.each(d.select(b[0]),function(i){var c=b[2]||"id";(i=i[c]?i[c].match(b[1]):null)&&a.push(i[1])});return a.length?a:null},initLink:function(a,b,i){if(i=g.link_target||i)a.target=i;a.rel="nofollow";a.href||(a.href=b.url);d.cache(a,"params",{exp:q,key:g.key,merchant:b.merchant,mid:b.mid,type:b.type||null});c.link(a)},insertLinks:function(){var i={timing:!1,
data:g.link_phrases?!1:g.link_urls},c=function(a,b){var i;i=d.createEl("a");i.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");i.className="vglnk";d.cache(i,"type","inserted");d.cache(i,"phrase",a);g.ui&&(i.title="Link added by VigLink");m.initLink(i,b);return i},r=function(i,n){for(var j,r,t,f,m=function(a){var b,a=!a||!g.per_phrase||!a.count||a.count<g.per_phrase;b=!g.per_page||e<g.per_page;return a&&b},o=function(b,i){var c,n,j,r,e,v,t,f,h,z,k=function(a){h.parentNode.insertBefore(b,
h);h.parentNode.removeChild(h);return a},A=function(a,b,i){a.x1-=i;a.y1-=i;a.x2+=i;a.y2+=i;return a.x1<b.x2&&a.x2>b.x1&&a.y1<b.y2&&a.y2>b.y1};h=d.createEl("span");b.parentNode.insertBefore(h,b);h.appendChild(b);z=d.geometry(h);if(g.proximity||g.same_proximity)for(v in a)if((t=a[v].links)&&!(a[v]===i&&!g.same_proximity||a[v]!==i&&!g.proximity)){f=a[v]===i?Math.max(g.same_proximity,g.proximity):g.proximity;for(c=0,n=t.length;c<n;c++){e=t[c].segments;for(j=0,r=e.length;j<r;j++)if(A(e[j].geometry,z,f))return k(!1)}}return k(!0)},
q=function(a,b){var i,c,n,j,v={el:a,segments:[]},e=a.getElementsByTagName("span"),r={els:[]};for(i=0,c=e.length;i<c;i++)n=e[i],void 0===j||n.offsetTop===j.offsetTop?r.els.push(n):(v.segments.push(r),r={els:[n]}),j=n;r.geometry=d.geometry.apply(d,r.els);v.segments.push(r);b.links=b.links||[];b.links.push(v);return b};i&&i.data&&Boolean(t=i.data.match(b));)r=t[0],f=t.slice(1).join(""),j=a[f.toLowerCase()],r=i.data.indexOf(r)+r.length-f.length,0<r&&(i=i.splitText(r)),r=i.length<=f.length?null:i.splitText(f.length),
f&&m(j)&&o(i,j)&&(j?"L"===j.type.toUpperCase()?h++:l++:(j={url:f.match(/^https?:\/\//i)?f:"http://"+f,type:"U"},k++),f=c(f,j),n(f,i),q(f,j),j.count++,e++),i=r},j=function(a){var i=b.test(a.data),c=a.parentNode;i&&r(a,function(a,b){c.insertBefore(a,b);c.removeChild(b)})},t=function(a){var b,i=function(a){return-1!==",a,applet,embed,object,head,img,input,link,map,meta,param,select,button,iframe,option,script,style,svg,textarea,title,".indexOf(","+a.nodeName.toLowerCase()+",")||d.hasClass(a,"nolinks")||
d.hasClass(a,"atma-nolink")||d.hasClass(a,"atma-no-link")};if(a){if(!i(a))for(b=a.firstChild;b;)a=b.nextSibling,1===b.nodeType?t(b):3===b.nodeType&&j(b),b=a}else d.each(d.select(g.scope),function(a){var b;a:for(var c=a;c.parentNode;)if(c=c.parentNode,1===c.nodeType&&i(c)){b=!0;break a}b||t(a)})};return function(a){i=d.extend(i,a);i.timing&&i.data&&b&&(t(),m.log())}}(),loadPhrases:function(b){var i,c,j,e=[];for(i=0,c=b.results.length;i<c;i++)j=b.results[i],j.phrase&&j.url&&(j.phrase=j.phrase.toLowerCase(),
a[j.phrase]||(e.push(j.phrase),a[j.phrase]={count:a[j.phrase]?a[j.phrase].count:0,phrase:j.phrase,merchant:j.merchant,mid:j.mid,url:j.url,type:j.type||""}));0<e.length&&this.addPhrasesToMatcher(e);this.insertLinks({data:!0})},log:function(){var b,i,c={heavy:[],lite:[]},j=function(a,b){return b.split(",")[0]-a.split(",")[0]};for(b in a)i=parseInt(a[b].count,10),0<i&&(i=[i,b.replace(/\|/g,"%7C")].join(),c["L"===a[b].type.toUpperCase()?"lite":"heavy"].push(i));c.lite.sort(j);c.heavy.sort(j);f("insert",
[{ct:e,cl:h,ch:l,cu:k,exp:q},{pl:c.lite.join("|")},{ph:c.heavy.join("|")}])},onInsertApi:function(a){"object"===d.type(a)&&a.results&&(q=a.exp,this.loadPhrases(a))},setup:function(){var a=d.bind(function(){this.getPhrases(this.getPostIDs())},this);g.scope=g.scope||o.scope||"body";g.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))",
"i"));if(g.link_phrases)if(!g.platform||"full"===g.platform)a();else d.on("DOMReady",a)}},m.setup())},run:function(){d.on("DOMReady",function(){m.insertLinks({timing:!0})})}};return y}();
(function(){function g(a,b,c,e,j,d){for(var j=0,f=e.length;j<f;j++){var g=e[j];if(g){for(var h=!1,g=g[a];g;){if(g.sizcache===c){h=e[g.sizset];break}1===g.nodeType&&!d&&(g.sizcache=c,g.sizset=j);if(g.nodeName.toLowerCase()===b){h=g;break}g=g[a]}e[j]=h}}}function d(b,c,e,d,j,t){for(var j=0,g=d.length;j<g;j++){var f=d[j];if(f){for(var h=!1,f=f[b];f;){if(f.sizcache===e){h=d[f.sizset];break}if(1===f.nodeType)if(t||(f.sizcache=e,f.sizset=j),"string"!==typeof c){if(f===c){h=!0;break}}else if(0<a.filter(c,
[f]).length){h=f;break}f=f[b]}d[j]=h}}}var c=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,f=0,o=Object.prototype.toString,m=!1,q=!0;[0,0].sort(function(){q=!1;return 0});var a=function(i,n,d,r){var d=d||[],j=n=n||document;if(1!==n.nodeType&&9!==n.nodeType)return[];if(!i||"string"!==typeof i)return d;var f,g,h,l,m,q=!0,x=a.isXML(n),p=[],s=i;do if(c.exec(""),f=c.exec(s))if(s=f[3],p.push(f[1]),f[2]){l=f[3];break}while(f);
if(1<p.length&&e.exec(i))if(2===p.length&&b.relative[p[0]])g=w(p[0]+p[1],n);else for(g=b.relative[p[0]]?[n]:a(p.shift(),n);p.length;)i=p.shift(),b.relative[i]&&(i+=p.shift()),g=w(i,g);else if(!r&&1<p.length&&9===n.nodeType&&!x&&b.match.ID.test(p[0])&&!b.match.ID.test(p[p.length-1])&&(f=a.find(p.shift(),n,x),n=f.expr?a.filter(f.expr,f.set)[0]:f.set[0]),n){f=r?{expr:p.pop(),set:k(r)}:a.find(p.pop(),1===p.length&&("~"===p[0]||"+"===p[0])&&n.parentNode?n.parentNode:n,x);g=f.expr?a.filter(f.expr,f.set):
f.set;for(0<p.length?h=k(g):q=!1;p.length;)f=m=p.pop(),b.relative[m]?f=p.pop():m="",null==f&&(f=n),b.relative[m](h,f,x)}else h=[];h||(h=g);h||a.error(m||i);if("[object Array]"===o.call(h))if(q)if(n&&1===n.nodeType)for(i=0;null!=h[i];i++)h[i]&&(!0===h[i]||1===h[i].nodeType&&a.contains(n,h[i]))&&d.push(g[i]);else for(i=0;null!=h[i];i++)h[i]&&1===h[i].nodeType&&d.push(g[i]);else d.push.apply(d,h);else k(h,d);l&&(a(l,j,d,r),a.uniqueSort(d));return d};a.uniqueSort=function(a){if(u&&(m=q,a.sort(u),m))for(var b=
1;b<a.length;b++)a[b]===a[b-1]&&a.splice(b--,1);return a};a.matches=function(b,c){return a(b,null,null,c)};a.matchesSelector=function(b,c){return 0<a(c,null,null,[b]).length};a.find=function(a,c,e){var d;if(!a)return[];for(var j=0,f=b.order.length;j<f;j++){var g,h=b.order[j];if(g=b.leftMatch[h].exec(a)){var k=g[1];g.splice(1,1);if("\\"!==k.substr(k.length-1)&&(g[1]=(g[1]||"").replace(/\\/g,""),d=b.find[h](g,c,e),null!=d)){a=a.replace(b.match[h],"");break}}}d||(d="undefined"!==typeof c.getElementsByTagName?
c.getElementsByTagName("*"):[]);return{set:d,expr:a}};a.filter=function(i,c,d,e){for(var j,f,g=i,h=[],k=c,m=c&&c[0]&&a.isXML(c[0]);i&&c.length;){for(var l in b.filter)if(null!=(j=b.leftMatch[l].exec(i))&&j[2]){var o,p,q=b.filter[l];p=j[1];f=!1;j.splice(1,1);if("\\"!==p.substr(p.length-1)){k===h&&(h=[]);if(b.preFilter[l])if(j=b.preFilter[l](j,k,d,h,e,m)){if(!0===j)continue}else f=o=!0;if(j)for(var s=0;null!=(p=k[s]);s++)if(p){o=q(p,j,s,k);var u=e^!!o;d&&null!=o?u?f=!0:k[s]=!1:u&&(h.push(p),f=!0)}if(void 0!==
o){d||(k=h);i=i.replace(b.match[l],"");if(!f)return[];break}}}if(i===g)if(null==f)a.error(i);else break;g=i}return k};a.error=function(a){throw"Syntax error, unrecognized expression: "+a;};var b=a.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,
CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(a){return a.getAttribute("href")}},relative:{"+":function(b,c){var d="string"===typeof c,e=d&&!/\W/.test(c),d=d&&!e;e&&(c=c.toLowerCase());for(var e=0,j=
b.length,f;e<j;e++)if(f=b[e]){for(;(f=f.previousSibling)&&1!==f.nodeType;);b[e]=d||f&&f.nodeName.toLowerCase()===c?f||!1:f===c}d&&a.filter(c,b,!0)},">":function(b,c){var d,e="string"===typeof c,j=0,f=b.length;if(e&&!/\W/.test(c))for(c=c.toLowerCase();j<f;j++){if(d=b[j])d=d.parentNode,b[j]=d.nodeName.toLowerCase()===c?d:!1}else{for(;j<f;j++)(d=b[j])&&(b[j]=e?d.parentNode:d.parentNode===c);e&&a.filter(c,b,!0)}},"":function(a,b,c){var e,j=f++,h=d;"string"===typeof b&&!/\W/.test(b)&&(e=b=b.toLowerCase(),
h=g);h("parentNode",b,j,a,e,c)},"~":function(a,b,c){var e,j=f++,h=d;"string"===typeof b&&!/\W/.test(b)&&(e=b=b.toLowerCase(),h=g);h("previousSibling",b,j,a,e,c)}},find:{ID:function(a,b,c){if("undefined"!==typeof b.getElementById&&!c)return(a=b.getElementById(a[1]))&&a.parentNode?[a]:[]},NAME:function(a,b){if("undefined"!==typeof b.getElementsByName){for(var c=[],e=b.getElementsByName(a[1]),d=0,f=e.length;d<f;d++)e[d].getAttribute("name")===a[1]&&c.push(e[d]);return 0===c.length?null:c}},TAG:function(a,
b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a[1])}},preFilter:{CLASS:function(a,b,c,d,e,f){a=" "+a[1].replace(/\\/g,"")+" ";if(f)return a;for(var f=0,g;null!=(g=b[f]);f++)g&&(e^(g.className&&0<=(" "+g.className+" ").replace(/[\t\n\r]/g," ").indexOf(a))?c||d.push(g):c&&(b[f]=!1));return!1},ID:function(a){return a[1].replace(/\\/g,"")},TAG:function(a){return a[1].toLowerCase()},CHILD:function(b){if("nth"===b[1]){b[2]||a.error(b[0]);b[2]=b[2].replace(/^\+|\s*/g,"");
var c=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec("even"===b[2]&&"2n"||"odd"===b[2]&&"2n+1"||!/\D/.test(b[2])&&"0n+"+b[2]||b[2]);b[2]=c[1]+(c[2]||1)-0;b[3]=c[3]-0}else b[2]&&a.error(b[0]);b[0]=f++;return b},ATTR:function(a,c,d,e,f,g){c=a[1]=a[1].replace(/\\/g,"");!g&&b.attrMap[c]&&(a[1]=b.attrMap[c]);a[4]=(a[4]||a[5]||"").replace(/\\/g,"");"~="===a[2]&&(a[4]=" "+a[4]+" ");return a},PSEUDO:function(i,d,e,f,j){if("not"===i[1])if(1<(c.exec(i[3])||"").length||/^\w/.test(i[3]))i[3]=a(i[3],null,null,d);else return i=
a.filter(i[3],d,e,1^j),e||f.push.apply(f,i),!1;else if(b.match.POS.test(i[0])||b.match.CHILD.test(i[0]))return!0;return i},POS:function(a){a.unshift(!0);return a}},filters:{enabled:function(a){return!1===a.disabled&&"hidden"!==a.type},disabled:function(a){return!0===a.disabled},checked:function(a){return!0===a.checked},selected:function(a){return!0===a.selected},parent:function(a){return!!a.firstChild},empty:function(a){return!a.firstChild},has:function(b,c,d){return!!a(d[3],b).length},header:function(a){return/h\d/i.test(a.nodeName)},
text:function(a){return"text"===a.type},radio:function(a){return"radio"===a.type},checkbox:function(a){return"checkbox"===a.type},file:function(a){return"file"===a.type},password:function(a){return"password"===a.type},submit:function(a){return"submit"===a.type},image:function(a){return"image"===a.type},reset:function(a){return"reset"===a.type},button:function(a){return"button"===a.type||"button"===a.nodeName.toLowerCase()},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)}},
setFilters:{first:function(a,b){return 0===b},last:function(a,b,c,d){return b===d.length-1},even:function(a,b){return 0===b%2},odd:function(a,b){return 1===b%2},lt:function(a,b,c){return b<c[3]-0},gt:function(a,b,c){return b>c[3]-0},nth:function(a,b,c){return c[3]-0===b},eq:function(a,b,c){return c[3]-0===b}},filter:{PSEUDO:function(c,d,e,f){var j=d[1],g=b.filters[j];if(g)return g(c,e,d,f);if("contains"===j)return 0<=(c.textContent||c.innerText||a.getText([c])||"").indexOf(d[3]);if("not"===j){d=d[3];
e=0;for(f=d.length;e<f;e++)if(d[e]===c)return!1;return!0}a.error(j)},CHILD:function(a,b){var c=b[1],d=a;switch(c){case "only":case "first":for(;d=d.previousSibling;)if(1===d.nodeType)return!1;if("first"===c)return!0;d=a;case "last":for(;d=d.nextSibling;)if(1===d.nodeType)return!1;return!0;case "nth":var c=b[2],e=b[3];if(1===c&&0===e)return!0;var f=b[0],g=a.parentNode;if(g&&(g.sizcache!==f||!a.nodeIndex)){for(var h=0,d=g.firstChild;d;d=d.nextSibling)1===d.nodeType&&(d.nodeIndex=++h);g.sizcache=f}d=
a.nodeIndex-e;return 0===c?0===d:0===d%c&&0<=d/c}},ID:function(a,b){return 1===a.nodeType&&a.getAttribute("id")===b},TAG:function(a,b){return"*"===b&&1===a.nodeType||a.nodeName.toLowerCase()===b},CLASS:function(a,b){return-1<(" "+(a.className||a.getAttribute("class"))+" ").indexOf(b)},ATTR:function(a,c){var d=c[1],d=b.attrHandle[d]?b.attrHandle[d](a):null!=a[d]?a[d]:a.getAttribute(d),e=d+"",f=c[2],g=c[4];return null==d?"!="===f:"="===f?e===g:"*="===f?0<=e.indexOf(g):"~="===f?0<=(" "+e+" ").indexOf(g):
!g?e&&!1!==d:"!="===f?e!==g:"^="===f?0===e.indexOf(g):"$="===f?e.substr(e.length-g.length)===g:"|="===f?e===g||e.substr(0,g.length+1)===g+"-":!1},POS:function(a,c,d,e){var f=b.setFilters[c[2]];if(f)return f(a,d,c,e)}}},e=b.match.POS,h=function(a,b){return"\\"+(b-0+1)},l;for(l in b.match)b.match[l]=RegExp(b.match[l].source+/(?![^\[]*\])(?![^\(]*\))/.source),b.leftMatch[l]=RegExp(/(^(?:.|\r|\n)*?)/.source+b.match[l].source.replace(/\\(\d+)/g,h));var k=function(a,b){a=Array.prototype.slice.call(a,0);
return b?(b.push.apply(b,a),b):a};try{Array.prototype.slice.call(document.documentElement.childNodes,0)}catch(y){k=function(a,b){var c=0,d=b||[];if("[object Array]"===o.call(a))Array.prototype.push.apply(d,a);else if("number"===typeof a.length)for(var e=a.length;c<e;c++)d.push(a[c]);else for(;a[c];c++)d.push(a[c]);return d}}var u,s;document.documentElement.compareDocumentPosition?u=function(a,b){return a===b?(m=!0,0):!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition?
-1:1:a.compareDocumentPosition(b)&4?-1:1}:(u=function(a,b){var c,d,e=[],f=[];c=a.parentNode;d=b.parentNode;var g=c;if(a===b)return m=!0,0;if(c===d)return s(a,b);if(c){if(!d)return 1}else return-1;for(;g;)e.unshift(g),g=g.parentNode;for(g=d;g;)f.unshift(g),g=g.parentNode;c=e.length;d=f.length;for(g=0;g<c&&g<d;g++)if(e[g]!==f[g])return s(e[g],f[g]);return g===c?s(a,f[g],-1):s(e[g],b,1)},s=function(a,b,c){if(a===b)return c;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});a.getText=
function(b){for(var c="",d,e=0;b[e];e++)d=b[e],3===d.nodeType||4===d.nodeType?c+=d.nodeValue:8!==d.nodeType&&(c+=a.getText(d.childNodes));return c};(function(){var a=document.createElement("div"),c="script"+(new Date).getTime(),d=document.documentElement;a.innerHTML="<a name='"+c+"'/>";d.insertBefore(a,d.firstChild);document.getElementById(c)&&(b.find.ID=function(a,b,c){if("undefined"!==typeof b.getElementById&&!c)return(b=b.getElementById(a[1]))?b.id===a[1]||"undefined"!==typeof b.getAttributeNode&&
b.getAttributeNode("id").nodeValue===a[1]?[b]:void 0:[]},b.filter.ID=function(a,b){var c="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id");return 1===a.nodeType&&c&&c.nodeValue===b});d.removeChild(a);d=a=null})();(function(){var a=document.createElement("div");a.appendChild(document.createComment(""));0<a.getElementsByTagName("*").length&&(b.find.TAG=function(a,b){var c=b.getElementsByTagName(a[1]);if("*"===a[1]){for(var d=[],e=0;c[e];e++)1===c[e].nodeType&&d.push(c[e]);c=d}return c});
a.innerHTML="<a href='#'></a>";a.firstChild&&"undefined"!==typeof a.firstChild.getAttribute&&"#"!==a.firstChild.getAttribute("href")&&(b.attrHandle.href=function(a){return a.getAttribute("href",2)});a=null})();document.querySelectorAll&&function(){var c=a,d=document.createElement("div");d.innerHTML="<p class='TEST'></p>";if(!(d.querySelectorAll&&0===d.querySelectorAll(".TEST").length)){a=function(d,e,f,g){e=e||document;if(!g&&!a.isXML(e)){var h=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(d);if(h&&(1===
e.nodeType||9===e.nodeType)){if(h[1])return k(e.getElementsByTagName(d),f);if(h[2]&&b.find.CLASS&&e.getElementsByClassName)return k(e.getElementsByClassName(h[2]),f)}if(9===e.nodeType){if("body"===d&&e.body)return k([e.body],f);if(h&&h[3]){var l=e.getElementById(h[3]);if(l&&l.parentNode){if(l.id===h[3])return k([l],f)}else return k([],f)}try{return k(e.querySelectorAll(d),f)}catch(m){}}else if(1===e.nodeType&&"object"!==e.nodeName.toLowerCase()){var l=(h=e.getAttribute("id"))||"__sizzle__",n=e.parentNode,
o=/^\s*[+~]/.test(d);h?l=l.replace(/'/g,"\\$&"):e.setAttribute("id",l);o&&n&&(e=e.parentNode);try{if(!o||n)return k(e.querySelectorAll("[id='"+l+"'] "+d),f)}catch(p){}finally{h||e.removeAttribute("id")}}}return c(d,e,f,g)};for(var e in c)a[e]=c[e];d=null}}();(function(){var c=document.documentElement,d=c.matchesSelector||c.mozMatchesSelector||c.webkitMatchesSelector||c.msMatchesSelector,e=!1;try{d.call(document.documentElement,"[test!='']:sizzle")}catch(f){e=!0}d&&(a.matchesSelector=function(c,f){f=
f.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!a.isXML(c))try{if(e||!b.match.PSEUDO.test(f)&&!/!=/.test(f))return d.call(c,f)}catch(g){}return 0<a(f,null,null,[c]).length})})();(function(){var a=document.createElement("div");a.innerHTML="<div class='test e'></div><div class='test'></div>";a.getElementsByClassName&&0!==a.getElementsByClassName("e").length&&(a.lastChild.className="e",1!==a.getElementsByClassName("e").length&&(b.order.splice(1,0,"CLASS"),b.find.CLASS=function(a,b,c){if("undefined"!==
typeof b.getElementsByClassName&&!c)return b.getElementsByClassName(a[1])},a=null))})();a.contains=document.documentElement.contains?function(a,b){return a!==b&&(a.contains?a.contains(b):!0)}:document.documentElement.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:function(){return!1};a.isXML=function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?"HTML"!==a.nodeName:!1};var w=function(c,d){for(var e,f=[],g="",h=d.nodeType?[d]:d;e=b.match.PSEUDO.exec(c);)g+=
e[0],c=c.replace(b.match.PSEUDO,"");c=b.relative[c]?c+"*":c;e=0;for(var k=h.length;e<k;e++)a(c,h[e],f);return a.filter(g,f)};window.vglnk.Sizzle=a})();